# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# [START gke_boa_kubernetes_manifests_loadgenerator_deployment_loadgenerator]
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgenerator
  annotations:
    alpha.image.policy.openshift.io/resolve-names: '*'
    app.openshift.io/route-disabled: 'false'
    app.openshift.io/vcs-ref: ''
    app.openshift.io/vcs-uri: 'https://github.com/dzianis-shkindzerau/bank-of-anthos.git' 
    image.openshift.io/triggers: >-
      [{"from":{"kind":"ImageStreamTag","name":"loadgenerator:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"loadgenerator\")].image","pause":"false"}]
  labels:
    app: loadgenerator
    app.kubernetes.io/component: python-app
    app.kubernetes.io/instance: loadgenerator
    app.kubernetes.io/name: loadgenerator
    app.kubernetes.io/part-of: bank-of-anthos    
spec:
  selector:
    matchLabels:
      app: loadgenerator
  replicas: 1
  template:
    metadata:
      labels:
        app: loadgenerator
      # annotations:
      #   sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      restartPolicy: Always
      # securityContext:
      #   fsGroup: 1000
      #   runAsGroup: 1000
      #   runAsNonRoot: true
      #   runAsUser: 1000
      containers:
      - name: loadgenerator
        # securityContext:
        #   allowPrivilegeEscalation: false
        #   capabilities:
        #     drop:
        #       - all
        #   privileged: false
        #   readOnlyRootFilesystem: true
        image: image-registry.openshift-image-registry.svc:5000/epm-paas-dzianis-shkindzirau/loadgenerator:latest
        #image: gcr.io/bank-of-anthos-ci/loadgenerator:v0.5.10
        env:
        - name: FRONTEND_ADDR
          value: "frontend:80"
        - name: USERS
          value: "5"
        - name: LOG_LEVEL
          value: "error"
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            cpu: 250m
            memory: 1Gi
# [END gke_boa_kubernetes_manifests_loadgenerator_deployment_loadgenerator]

---

kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  annotations:
    app.openshift.io/vcs-uri: 'https://github.com/dzianis-shkindzerau/bank-of-anthos.git'
  name: loadgenerator
  labels:
    app: loadgenerator
    app.kubernetes.io/component: python-app
    app.kubernetes.io/instance: loadgenerator
    app.kubernetes.io/name: loadgenerator
    app.kubernetes.io/part-of: bank-of-anthos  
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'loadgenerator:latest'
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  source:
    type: Git
    git:
      uri: 'https://github.com/dzianis-shkindzerau/bank-of-anthos.git'
      ref: "develop"
    contextDir: /src/loadgenerator/
  triggers:
    # - type: Generic
    #   generic:
    #     secretReference:
    #       name: accounts-db-generic-webhook-secret
    # - type: GitHub
    #   github:
    #     secretReference:
    #       name: accounts-db-github-webhook-secret
    - type: ConfigChange
  runPolicy: Serial

---

kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: loadgenerator
  annotations:
    app.openshift.io/vcs-uri: 'https://github.com/dzianis-shkindzerau/bank-of-anthos.git'
  labels:
    app: loadgenerator
    app.kubernetes.io/component: python-app
    app.kubernetes.io/instance: loadgenerator
    app.kubernetes.io/name: loadgenerator
    app.kubernetes.io/part-of: bank-of-anthos 
spec:
  lookupPolicy:
    local: false